name: ContinuousD - Publicação da aplicação ao Azure Function
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Executando o Job de Compilação
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
        include-prerelease: True

    - name: Restore
      run: dotnet restore "FiapCloudGames.AzureFunctions"

    - name: Build
      run: dotnet build "FiapCloudGames.AzureFunctions" --configuration Release --no-restore

    - name: Publish
      run: dotnet publish "FiapCloudGames.AzureFunctions" --configuration Release --no-build --output "FiapCloudGames.AzureFunctions/published"

    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: functionapp
        path: FiapCloudGames.AzureFunctions/published

  deploy:
    name: Executando o Job de Publicação
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: functionapp
        path: FiapCloudGames.AzureFunctions/published

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: fiapcloudgames-azurefunctions
        package: FiapCloudGames.AzureFunctions/published